import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Page } from '../components/Page'

const Home: NextPage = () => {
  return (
    <Page>
      <Head>
        <title>Talk on Solana - Talkana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
     
    </Page>
  )
}

export default Home
